[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  # Forward every call that starts with /api
  from = "/api/*"
  to = "http://13.201.91.4:8000/:splat"
  status = 200
  force = true

[[redirects]]
  # Handle client-side routing - redirect all other requests to index.html
  from = "/*"
  to = "/index.html"
  status = 200